# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home3/317/team10/Downloads/PYNQ-Z2_v1.0.xdc

# Block Designs: bd/vhdlparkinglotblockdesign/vhdlparkinglotblockdesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vhdlparkinglotblockdesign || ORIG_REF_NAME==vhdlparkinglotblockdesign} -quiet] -quiet

# IP: bd/vhdlparkinglotblockdesign/ip/vhdlparkinglotblockdesign_ParkingFSM_0_0/vhdlparkinglotblockdesign_ParkingFSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vhdlparkinglotblockdesign_ParkingFSM_0_0 || ORIG_REF_NAME==vhdlparkinglotblockdesign_ParkingFSM_0_0} -quiet] -quiet

# XDC: bd/vhdlparkinglotblockdesign/vhdlparkinglotblockdesign_ooc.xdc
